modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="xp_backrooms"
version="0.4.3"
displayName="XP Backrooms (Java port)"
description='''
Personal Java port of the Bacteria mob from the Bedrock BACKROOMS Add-On.
'''

[[dependencies.xp_backrooms]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.xp_backrooms]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.xp_backrooms]]
modId="geckolib"
mandatory=true
versionRange="[4.4,)"
ordering="AFTER"
side="BOTH"
